### ISSUE TITLE
FIVEM ERROR GET INFORMATIONS... RETRY LATER

### ISSUE THREAD

**Issue by Quentins84004** [WhySimply/DiscordFiveMPlayers#1]
Hello i have this issue after following the initialization steps : FIVEM ERROR GET INFORMATIONS... RETRY LATER

How can i fix  this ?
<img width="979" alt="Capture d’écran 2023-07-02 à 22 42 55" src="https://github.com/WhySimply/DiscordFiveMPlayers/assets/138402819/0c08d65e-1473-4397-9aef-22a4670b0633">

**Comment by WhySimply** [comment]
@Quentins84004 

I have just updated the script which works again, be careful to take the latest version and fill in the correct variables, I remain available if ever
